version: 2.1

jobs:
  create_network_resources:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Network resources
          command: |
            aws cloudformation create-stack \
              --template-body network.yml \
              --stack-name network_infra \
              --parameters network-parameters.json

workflows:
  my_workflow:
    jobs:
      - create_network_resources:
          context: awscredentials
